## 注册

POST http://localhost:8000/api/user/register
Content-Type: application/json

{"username": "fujie", "password": "f447b20a7fcbf53a5d5be013ea0b15af", "email": "fujie.me@qq.com", "phone": "15596207601"}

###

## 登录
POST http://localhost:8000/api/user/login
Content-Type: application/json

{"username": "fujie", "password": "f447b20a7fcbf53a5d5be013ea0b15af"}

###

GET http://localhost:8000/api/user/myInfo
Cookie: sessionid=wsog1u6jgr9d2w4r3ejmantvvttszir7; expires=Wed, 20 May 2020 13:58:38 GMT; HttpOnly; Max-Age=1209600; Path=/; SameSite=Lax

###
