## 注册

POST http://localhost:8000/api/user/register
Content-Type: application/json

{"username": "fujie", "password": "f447b20a7fcbf53a5d5be013ea0b15af", "email": "fujie.me@qq.com", "phone": "15596207601"}

###

## 登录
POST http://localhost:8000/api/user/login
Content-Type: application/json

{"username": "fujie", "password": "f447b20a7fcbf53a5d5be013ea0b15af"}

###

GET http://localhost:8000/api/user/myInfo
Cookie: sessionid=cksulhv65s8gaikcuq9svuldweph71l7;

###
